### ISSUE TITLE
 (UndefinedFunctionError) function :string_lexer.string/1 is undefined (module :string_lexer is not available)

### ISSUE THREAD

**Issue by alabama** [RobertDober/earmark_parser#135]
I'm using `phoenix_storybook` and upgraded it to 0.5.6 from 0.5.3. The hex dependencies to earmark and earmark_parser changed as well from:

```
  "earmark": {:hex, :earmark, "1.4.37", "56ce845c543393aa3f9b294c818c3d783452a4a67e4ab18c4303a954a8b59363", [:mix], [{:earmark_parser, "~> 1.4.31", [hex: :earmark_parser, repo: "hexpm", optional: false]}], "hexpm", "d86d5e12868db86d5321b00e62a4bbcb4150346e4acc9a90a041fb188a5cb106"},
  "earmark_parser": {:hex, :earmark_parser, "1.4.31", "a93921cdc6b9b869f519213d5bc79d9e218ba768d7270d46fdcf1c01bacff9e2", [:mix], [], "hexpm", "317d367ee0335ef037a87e46c91a2269fef6306413f731e8ec11fc45a7efd059"},
```

to:

```
  "earmark": {:hex, :earmark, "1.4.42", "ede2231e5d5a1975e198f2a05368fb3abec3cd071caf833e05479f840b5d41f2", [:mix], [], "hexpm", "80f6451b0615e19250d8a57cdea1580fa433295e0e7939a530dfea3b62616094"},
  "earmark_parser": {:hex, :earmark_parser, "1.4.35", "437773ca9384edf69830e26e9e7b2e0d22d2596c4a6b17094a3b29f01ea65bb8", [:mix], [], "hexpm", "8652ba3cb85608d0d7aa2d21b45c6fad4ddc9a1f9a1f1b30ca3a246f0acc33f6"},
```

I build my project within docker with the image: `FROM hexpm/elixir:1.14.2-erlang-25.2-ubuntu-jammy-20220428`

Everything worked fine before the upgrade, afterwards this error occured on the step:
`RUN mix do deps.get, compile`

```
322.1 ==> phoenix_storybook
322.1 Compiling 44 files (.ex)
325.0
325.0 == Compilation error in file lib/phoenix_storybook/guides/guides.ex ==
325.0 ** (UndefinedFunctionError) function :string_lexer.string/1 is undefined (module :string_lexer is not available)
325.0     :string_lexer.string('Basic component documentation is in `PhoenixStorybook.Story`.')
325.0     (earmark 1.4.42) lib/earmark_parser/helpers/leex_helpers.ex:20: EarmarkParser.Helpers.LeexHelpers.tokenize/2
325.0     (earmark 1.4.42) lib/earmark_parser/helpers/lookahead_helpers.ex:17: EarmarkParser.Helpers.LookaheadHelpers.opens_inline_code/1
325.0     (earmark 1.4.42) lib/earmark_parser/parser.ex:658: EarmarkParser.Parser._inline_or_text?/2
325.0     (earmark 1.4.42) lib/earmark_parser/parser.ex:486: EarmarkParser.Parser._consolidate_para/4
325.0     (earmark 1.4.42) lib/earmark_parser/parser.ex:215: EarmarkParser.Parser._parse/4
325.0     (earmark 1.4.42) lib/earmark_parser/parser.ex:68: EarmarkParser.Parser.lines_to_blocks/3
325.0     (earmark 1.4.42) lib/earmark_parser/parser.ex:60: EarmarkParser.Parser.parse_lines/3
325.0 could not compile dependency :phoenix_storybook, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile phoenix_storybook", update it with "mix deps.update phoenix_storybook" or clean it with "mix deps.clean phoenix_storybook"
```

I just reverted both earmark deps back to before and it works again. I couldn't figure out what I'm missing because the `deps/earmark_parser/src/string_lexer.erl` did not change through the versions.
Any suggestions?

**Comment by RobertDober** [comment]
I appologize but you need to upgrade to Earmark 1.4.43 where this misstake has been fixed. 
My appologies for the bad versions 1.4.41 and 1.4.42
