### ISSUE TITLE
** (ArgumentError) argument error in lib/earmark_parser/line_scanner.ex:144

### ISSUE THREAD

**Issue by kianmeng** [RobertDober/earmark_parser#80]
I've tested this in Earmark `1.14.18` and latest `master`.

See https://github.com/rbino/qoix/compare/main...kianmeng:line-scanner-error

To reproduce the error:

```sh
git clone https://github.com/kianmeng/qoix.git
cd qoix
git checkout line-scanner-error
mix deps.get
mix docs
```

Error encountered:

```sh
** (ArgumentError) argument error
    (stdlib 3.16.1) :re.run(<<32, 32, 32, 32, 32, 32, 112, 105, 120, 101, 108, 115, 58, 32, 34, 137, 80, 78, 71>>, {:re_pattern, 2, 1, 0, <<69, 82, 67, 80, 126, 0, 0, 0, 16, 8, 0, 32, 1, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, [{:capture, :all, :binary}, {:offset, 0}])
    (elixir 1.13.0) lib/regex.ex:481: Regex.safe_run/3
    (elixir 1.13.0) lib/regex.ex:329: Regex.run/3
    (earmark_parser 1.4.18) lib/earmark_parser/line_scanner.ex:144: EarmarkParser.LineScanner._type_of/3
    (earmark_parser 1.4.18) lib/earmark_parser/line_scanner.ex:107: EarmarkParser.LineScanner.type_of/3
    (earmark_parser 1.4.18) lib/earmark_parser/line_scanner.ex:66: EarmarkParser.LineScanner.with_lookahead/3
    (earmark_parser 1.4.18) lib/earmark_parser/line_scanner.ex:85: EarmarkParser.LineScanner.with_lookahead/3
    (earmark_parser 1.4.18) lib/earmark_parser/parser.ex:45: EarmarkParser.Parser.parse/3
```

See [this line](https://github.com/rbino/qoix/compare/main...kianmeng:line-scanner-error#diff-a43ec01c10c0aeb6b76eb17103ae625ebb72c32e34d61de9c6a9609e2d8c48eaR38) that triggered the error:

```elixir
pixels: "\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\x02*" <> ...,
```

Probably the regression of https://github.com/RobertDober/earmark_parser/pull/79 ?

**Comment by RobertDober** [comment]
@kianmeng can you please just paste the line which triggers the error? The link above seems to be broken

**Comment by kianmeng** [comment]
@RobertDober I've fixed the link. Sorry about that.

You meant that the below code block was not treated as legal UTF-8 string, especially the line that contains `:pixels` field?

```elixir
  ## Examples

      iex> image = File.read!("test/support/images/elixir-logo.png")
      iex> Qoix.Image.from_rgb(554, 690, image)
      %Qoix.Image{
        colorspace: :srgb,
        format: :rgb,
        height: 690,
        pixels: "\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\x02*" <> ...,
        width: 554
      }
```

**Comment by RobertDober** [comment]
That would be my guess, because if I copy just the pixels head string like that
```iex
iex(6)> "\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\x02*"
<<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2, 42>>
iex(7)> ["\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\x02*"] |> EarmarkParser.LineScanner.scan_lines
** (ArgumentError) argument error
    (stdlib 3.16.1) :re.run(<<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2, 42>>, {:re_pattern, 2, 1, 0, <<69, 82, 67, 80, 126, 0, 0, 0, 16, 8, 0, 32, 1, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, [{:capture, :all, :binary}, {:offset, 0}])
    (elixir 1.13.0) lib/regex.ex:481: Regex.safe_run/3
    (elixir 1.13.0) lib/regex.ex:329: Regex.run/3
    (earmark_parser 1.4.19) lib/earmark_parser/line_scanner.ex:134: EarmarkParser.LineScanner._type_of/3
    (earmark_parser 1.4.19) lib/earmark_parser/line_scanner.ex:97: EarmarkParser.LineScanner.type_of/3
    (earmark_parser 1.4.19) lib/earmark_parser/line_scanner.ex:66: EarmarkParser.LineScanner.with_lookahead/3
``` 
I get the same error and I do not see an easy way to avoid that.

I do not think we should be able to treat that kind of raw bytes.
I suspect you get the error when using `ex_doc`  e.g. by calling the `mix doc` task?

If that is the case it might be possible to adapt your doctest 

```
iex> image = File.read!("test/support/images/elixir-logo.png")
      iex> Qoix.Image.from_rgb(554, 690, image)
      %Qoix.Image{
        colorspace: :srgb,
        format: :rgb,
        height: 690,
        pixels: <<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2, 42>>
        width: 554
```
or something similar.

Binary data in doctests is a sticky wicket (old expression from cricket to indicate a tricky issue)
maybe you should ask for help in `ex_doc`'s git repo/Elixir Forum

**Comment by RobertDober** [comment]
A last remark if ex_doc passes the bitstring in as the content of the string, the parser would worl

```elxir
["<<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2, 42>>"] |> EarmarkParser.as_ast                
{:ok,
 [
   {"p", [],
    ["<<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2, 42>>"],
    %{}}
 ], []}
```

**Comment by RobertDober** [comment]
But maybe this is a bug, I really need to check with  `ex_doc` please stand by

**Comment by RobertDober** [comment]
@kianmeng https://github.com/elixir-lang/ex_doc/issues/1451

that said it would really be cool if you can rewrite your source file to be UTF8 😉

**Comment by RobertDober** [comment]
@kianmeng  José just confirmed what I suspected, you need to _fix_ your text to be UTF-8 

https://github.com/elixir-lang/ex_doc/issues/1451#issuecomment-1001607291

**Comment by kianmeng** [comment]
@RobertDober Thank you for the quick response and investigation. :+1: :tada:
