### ISSUE TITLE
v1.4.19 causes Earmark to throw an exception

### ISSUE THREAD

**Issue by conradfr** [RobertDober/earmark_parser#84]
Hello,

It seems v1.4.19 causes all recent versions of Earmark to crash when callling as_html/2, while it works when using EarmarkParser v1.1.18.

`Earmark.as_html("Hello World")`

```** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in MapSet.union/2
        (elixir 1.13.1) lib/map_set.ex:372: MapSet.union([], [])
        (earmark_parser 1.4.19) lib/earmark_parser/context.ex:64: EarmarkParser.Context._merge_messages/2
        (earmark_parser 1.4.19) lib/earmark_parser/context.ex:55: EarmarkParser.Context._merge_contexts/2
        (earmark_parser 1.4.19) lib/earmark_parser/context.ex:47: EarmarkParser.Context.prepend/3
        (earmark_parser 1.4.19) lib/earmark_parser/ast_renderer.ex:23: EarmarkParser.AstRenderer._render/3
        (earmark_parser 1.4.19) lib/earmark_parser.ex:494: EarmarkParser.as_ast/2
        (earmark 1.4.19) lib/earmark/internal.ex:42: Earmark.Internal.as_html/2
        (earmark 1.4.19) lib/earmark/internal.ex:48: Earmark.Internal.as_html!/2`

**Comment by RobertDober** [comment]
I appologize for this I will release a bug fix, in Earmark, as this version was not meant for Earmark.
