### ISSUE TITLE
Code blocks near list items are interpreted as text

### ISSUE THREAD

**Issue by RobertDober** [RobertDober/earmark_parser#9]
https://github.com/pragdave/earmark/issues/349

Here is the original issue

```
    code = """
    * List item

      Text

        * List item

      Text

          https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}

    """

    IO.inspect Earmark.as_ast(code)
```

results in:

```
     ** (ArgumentError) malformed URI "https://mydomain.org/user_or_team/repo_name/blob/master/%"
     code: IO.inspect Earmark.as_ast(code)
     stacktrace:
       (elixir 1.10.2) lib/uri.ex:344: URI.decode/1
       (earmark 1.4.5) lib/earmark/helpers/ast_helpers.ex:58: Earmark.Helpers.AstHelpers.render_link/2
       (earmark 1.4.5) lib/earmark/helpers/pure_link_helpers.ex:25: Earmark.Helpers.PureLinkHelpers.determine_ending_parens_by_count/3
       (earmark 1.4.5) lib/earmark/ast/inline.ex:100: Earmark.Ast.Inline.converter_for_pure_link/1
```

An easy workaround in the meantime is to change:

```
    https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}
```

to:

    ```
    https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}
    ```

P.S. I found this when running `cd /path/to/ex_doc && mix build` on Earmark 1.4.5, I'll use the workaround on ExDoc master soon.

**Comment by RobertDober** [comment]
need to follow the discussion in the original issue

**Comment by RobertDober** [comment]
Although making progress the solution will introduce backward incompatibilities, hence-for  -> 1.5

**Comment by kianmeng** [comment]
@RobertDober Is this fix related to this ticket, https://github.com/elixir-lang/ex_doc/issues/1286?
